# Generated by Django 3.0.3 on 2020-08-10 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=None, max_length=256, verbose_name='评价内容')),
            ],
        ),
        migrations.CreateModel(
            name='Del_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改时间')),
                ('content', models.CharField(max_length=10240, verbose_name='文档内容')),
                ('title', models.CharField(max_length=32, verbose_name='文档标题')),
            ],
        ),
        migrations.CreateModel(
            name='Document_through_BrowseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edit_time', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('Document', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Document', verbose_name='被浏览文档')),
            ],
        ),
        migrations.CreateModel(
            name='Document_through_CollectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collect_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('Document', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Document', verbose_name='被收藏文档')),
            ],
        ),
        migrations.CreateModel(
            name='Document_through_EditUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edit_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('Document', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Document', verbose_name='被修改文档')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_name', models.CharField(default=None, max_length=32, verbose_name='文件夹名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='File_through_EditUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edit_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('File', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.File', verbose_name='被修改文件夹')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('content', models.CharField(default=None, max_length=64, verbose_name='文本内容')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('level', models.IntegerField(default=0, verbose_name='权限等级')),
                ('Document', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Document', verbose_name='文档')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=None, max_length=256, verbose_name='团队描述')),
                ('team_name', models.CharField(max_length=64, verbose_name='团队名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=64, verbose_name='用户名')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='User_through_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('Team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Team', verbose_name='团队')),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.User', verbose_name='团队成员')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='team',
            name='memebers',
            field=models.ManyToManyField(through='firstapp.User_through_Team', to='firstapp.User'),
        ),
        migrations.AddField(
            model_name='permission',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='message',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.User', verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='file_through_edituser',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.User', verbose_name='修改者'),
        ),
        migrations.AddField(
            model_name='file',
            name='EditUsers',
            field=models.ManyToManyField(related_name='File_EditUsers', through='firstapp.File_through_EditUser', to='firstapp.User'),
        ),
        migrations.AddField(
            model_name='file',
            name='Team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Team', verbose_name='团队'),
        ),
        migrations.AddField(
            model_name='file',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to='firstapp.User', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='document_through_edituser',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.User', verbose_name='修改者'),
        ),
        migrations.AddField(
            model_name='document_through_collectuser',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.User', verbose_name='收藏者'),
        ),
        migrations.AddField(
            model_name='document_through_browseuser',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.User', verbose_name='浏览者'),
        ),
        migrations.AddField(
            model_name='document',
            name='BrowseUsers',
            field=models.ManyToManyField(related_name='BrowseUsers', through='firstapp.Document_through_BrowseUser', to='firstapp.User'),
        ),
        migrations.AddField(
            model_name='document',
            name='CollectUsers',
            field=models.ManyToManyField(related_name='CollectUsers', through='firstapp.Document_through_CollectUser', to='firstapp.User'),
        ),
        migrations.AddField(
            model_name='document',
            name='EditUsers',
            field=models.ManyToManyField(related_name='Document_EditUsers', through='firstapp.Document_through_EditUser', to='firstapp.User'),
        ),
        migrations.AddField(
            model_name='document',
            name='Team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Team', verbose_name='团队'),
        ),
        migrations.AddField(
            model_name='document',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.User', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.File', verbose_name='所属文件夹'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Document',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Document', verbose_name='被评论文档'),
        ),
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.User', verbose_name='评论者'),
        ),
    ]
