# Generated by Django 3.0.3 on 2020-08-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20200810_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_email',
            field=models.EmailField(default=None, max_length=254, verbose_name='邮箱'),
        ),
    ]
