# Generated by Django 3.0.3 on 2020-08-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_user_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(verbose_name='文档内容'),
        ),
    ]
