# Generated by Django 3.0.3 on 2020-08-12 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20200811_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='level',
        ),
        migrations.AddField(
            model_name='document',
            name='AuthorityUsers',
            field=models.ManyToManyField(related_name='Document_AuthorityUsers', through='firstapp.Permission', to='firstapp.User', verbose_name='权限列表'),
        ),
        migrations.AddField(
            model_name='document',
            name='judgeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='model',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='recycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='Team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Team', verbose_name='团队'),
        ),
        migrations.AddField(
            model_name='permission',
            name='five',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='four',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='two',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='creater',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to='firstapp.User', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='document',
            name='BrowseUsers',
            field=models.ManyToManyField(related_name='BrowseUsers', through='firstapp.Document_through_BrowseUser', to='firstapp.User', verbose_name='浏览用户记录'),
        ),
        migrations.AlterField(
            model_name='document',
            name='CollectUsers',
            field=models.ManyToManyField(related_name='CollectUsers', through='firstapp.Document_through_CollectUser', to='firstapp.User', verbose_name='收藏用户列表'),
        ),
        migrations.AlterField(
            model_name='document',
            name='EditUsers',
            field=models.ManyToManyField(related_name='Document_EditUsers', through='firstapp.Document_through_EditUser', to='firstapp.User', verbose_name='修改用户记录'),
        ),
        migrations.AlterField(
            model_name='document',
            name='Team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Team', verbose_name='团队'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.File', verbose_name='所属文件夹'),
        ),
        migrations.AlterField(
            model_name='team',
            name='memebers',
            field=models.ManyToManyField(related_name='menebers', through='firstapp.User_through_Team', to='firstapp.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, upload_to='', verbose_name='头像'),
        ),
    ]
